export const UPDATE_NEW_RECIPE_TITLE = 'UPDATE_NEW_RECIPE_TITLE';
export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCESS';
export const CREATE_RECIPE_FAIL = 'CREATE_RECIPE_FAIL';
export const LOAD_RECIPES_SUCCESS = 'LOAD_RECIPES_SUCCESS';
